name: leeambrose
favicon: null
layout_spectrum: 0.6843908096197993
typography_spectrum: 0.5105951523873955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.11876534880138934
  lightness: 0.3680555294267833
  saturation: 0.8297921370249242
  rhythmicContrast: 0.18264350318349898
purpose: []
